import { notFound } from "next/navigation";
import Link from "next/link";
import { requireUser } from "@/lib/auth";
import { formatMoney } from "@/lib/catalogue";

export default async function OrderDetail({ params }: { params: Promise<{ id: string }> }) {
  const { supabase, userId } = await requireUser(); const { id } = await params;
  const { data: order } = await supabase.from("orders").select("id,merchant_reference,status,amount_minor,currency,created_at,order_items(title_snapshot,product_type),payments(status,provider_payment_reference,established_at),fulfilments(status,carrier,tracking_reference,dispatched_at)").eq("id", id).eq("customer_id", userId).maybeSingle();
  if (!order) notFound();
  const item = Array.isArray(order.order_items) ? order.order_items[0] : order.order_items; const payment = Array.isArray(order.payments) ? order.payments[0] : order.payments; const fulfilment = Array.isArray(order.fulfilments) ? order.fulfilments[0] : order.fulfilments;
  return <div className="shell py-14"><Link href="/account/orders">← Purchase history</Link><div className="card mt-6 p-7 md:p-10"><p className="eyebrow">Merchant reference</p><h1 className="display mt-2 text-4xl">{order.merchant_reference}</h1><dl className="mt-8 grid gap-5 sm:grid-cols-2"><div><dt className="muted text-sm">Product</dt><dd className="font-bold">{item?.title_snapshot}</dd></div><div><dt className="muted text-sm">Merchant amount</dt><dd className="font-bold">{formatMoney(order.amount_minor, order.currency)} {order.currency}</dd></div><div><dt className="muted text-sm">Purchase status</dt><dd className="font-bold capitalize">{order.status.replaceAll("_", " ")}</dd></div><div><dt className="muted text-sm">Payment status</dt><dd className="font-bold capitalize">{payment?.status ?? "Not confirmed"}</dd></div></dl>{order.status !== "paid" && <p className="notice mt-7">This purchase is not confirmed as paid. Fulfilment and access have not been granted.</p>}{fulfilment && <section className="mt-8 border-t border-[var(--line)] pt-7"><h2 className="display text-3xl">Delivery</h2><p className="mt-3 font-bold capitalize">{fulfilment.status.replaceAll("_", " ")}</p>{fulfilment.status === "awaiting_fulfilment" && <p className="muted">Payment is confirmed and the order is awaiting preparation. It has not been dispatched.</p>}{fulfilment.dispatched_at && <p className="muted">Dispatched {new Date(fulfilment.dispatched_at).toLocaleDateString("en-GB")}{fulfilment.carrier ? ` with ${fulfilment.carrier}` : ""}{fulfilment.tracking_reference ? `. Tracking: ${fulfilment.tracking_reference}` : ""}</p>}</section>}{item?.product_type === "digital" && order.status === "paid" && <Link className="button mt-8" href="/library">Open your digital book</Link>}{item?.product_type === "subscription" && order.status === "paid" && <Link className="button mt-8" href="/library">Open the Reading Room</Link>}</div></div>;
}
