import { notFound } from "next/navigation";
import { requireUser } from "@/lib/auth";
import { formatMoney, getProduct } from "@/lib/catalogue";
import { beginCheckout } from "../actions";
import { resolveAccountProfile } from "@/lib/account-profile";
import { redirect } from "next/navigation";

export default async function CheckoutReview({ params, searchParams }: { params: Promise<{ slug: string }>; searchParams: Promise<{ message?: string }> }) {
  const product = getProduct((await params).slug); if (!product) notFound();
  const { supabase, userId } = await requireUser();
  const profileResult = await supabase.from("profiles").select("id, display_name, market").eq("id", userId).maybeSingle();
  const profileState = resolveAccountProfile(userId, profileResult);
  if (profileState.status === "unavailable") redirect("/account?message=Your+saved+profile+must+be+available+before+starting+a+purchase");
  const { message } = await searchParams;
  const market = profileState.profile.market;
  return <div className="shell py-14"><div className="mx-auto max-w-2xl"><p className="eyebrow">Review before payment</p><h1 className="display mt-2 text-5xl">{product.title}</h1>{message && <p className="notice mt-6" role="status">{message}</p>}<div className="card mt-8 p-7"><div className="flex justify-between gap-5 border-b border-[var(--line)] pb-5"><div><p className="font-bold">{product.title}</p><p className="muted">{product.kind === "subscription" ? "Recurring monthly membership" : `One-time ${product.kind} purchase`}</p></div><p className="font-bold">{formatMoney(product.amountMinor, product.currency)}{product.interval && "/month"}</p></div><p className="mt-5 font-bold">Total authorized today: {formatMoney(product.amountMinor, product.currency)}</p><p className="muted text-sm">Transaction currency: {product.currency}. Your card issuer may apply its own conversion or fees.</p>{product.interval && <p className="notice mt-5">This subscription renews automatically at {formatMoney(product.amountMinor, product.currency)} every month until cancelled. It provides the continuing Reading Room library and monthly releases.</p>}
      <form action={beginCheckout} className="mt-7 grid gap-5"><input type="hidden" name="slug" value={product.slug} />{product.kind === "physical" && <fieldset className="grid gap-4"><legend className="display mb-3 text-2xl">Delivery address</legend><div className="field"><label htmlFor="recipient_name">Recipient name</label><input id="recipient_name" name="recipient_name" autoComplete="name" required /></div><div className="field"><label htmlFor="line1">Address line 1</label><input id="line1" name="line1" autoComplete="address-line1" required /></div><div className="field"><label htmlFor="line2">Address line 2 (optional)</label><input id="line2" name="line2" autoComplete="address-line2" /></div><div className="grid gap-4 sm:grid-cols-2"><div className="field"><label htmlFor="city">City</label><input id="city" name="city" autoComplete="address-level2" required /></div><div className="field"><label htmlFor="region">{market === "AE" ? "Emirate" : "County / region"}</label><input id="region" name="region" autoComplete="address-level1" required /></div></div><div className="grid gap-4 sm:grid-cols-2"><div className="field"><label htmlFor="postal_code">Postal code (if applicable)</label><input id="postal_code" name="postal_code" autoComplete="postal-code" /></div><div className="field"><label htmlFor="phone">Phone</label><input id="phone" name="phone" type="tel" autoComplete="tel" required /></div></div><input type="hidden" name="country_code" value={market} /><p className="muted text-sm">Delivering to {market === "AE" ? "United Arab Emirates" : "United Kingdom"}. Delivery is included.</p></fieldset>}<button className="button" type="submit">Continue to secure Stripe payment</button><p className="muted text-center text-sm">Sandbox checkout only. Do not enter real card details.</p></form></div></div></div>;
}
