import { requireStaff } from "@/lib/staff";
import { createAdminClient } from "@/lib/supabase/admin";
import { updateFulfilment } from "./actions";

export default async function StaffFulfilmentPage() {
  await requireStaff();
  const { data: fulfilments } = await createAdminClient().from("fulfilments").select("order_id,status,address_snapshot,carrier,tracking_reference,orders!inner(merchant_reference,status,order_items(title_snapshot))").neq("status", "cancelled").order("updated_at", { ascending: false });
  return <div className="shell py-14"><p className="eyebrow">Restricted staff operation</p><h1 className="display mt-2 text-5xl">Physical fulfilment</h1><p className="notice mt-5">Only record states that have actually been established. Dispatch requires a real dispatch action; tracking is optional unless supplied.</p><div className="mt-8 grid gap-5">{fulfilments?.map((row) => { const order = Array.isArray(row.orders) ? row.orders[0] : row.orders; const item = Array.isArray(order?.order_items) ? order.order_items[0] : order?.order_items; return <form action={updateFulfilment} className="card grid gap-4 p-6" key={row.order_id}><input type="hidden" name="orderId" value={row.order_id} /><p className="font-bold">{item?.title_snapshot}</p><p className="muted">{order?.merchant_reference} · {order?.status.replaceAll("_", " ")}</p><p className="muted">Current: {row.status.replaceAll("_", " ")}</p><div className="grid gap-4 md:grid-cols-3"><div className="field"><label>Status</label><select name="status" defaultValue={row.status === "awaiting_fulfilment" ? "preparing" : row.status}><option value="preparing">Preparing</option><option value="dispatched">Dispatched</option><option value="cancelled">Cancelled</option></select></div><div className="field"><label>Carrier (optional)</label><input name="carrier" defaultValue={row.carrier ?? ""} /></div><div className="field"><label>Tracking reference (optional)</label><input name="tracking" defaultValue={row.tracking_reference ?? ""} /></div></div><button className="button justify-self-start">Record established state</button></form>; })}</div></div>;
}
